### ISSUE TITLE
Docker container cannot start server

### ISSUE THREAD

**Issue by shadow7412** [ich777/docker-terraria-server#10]
```
---Checking if UID: 99 matches user---
usermod: no changes
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Starting...---
---Version Check---
---Terraria not found, downloading!---
terraria-server-144 100%[===================>]  42.56M  12.9MB/s    in 3.3s    
---Successfully downloaded Terraria---
---Prepare Server---
---Server ready---
---Checking for old logs---
---Start Server---
tail: cannot open '/serverdata/serverfiles/masterLog.0' for reading: No such file or directory
tail: no files remaining
```

As you can see, it seems to successfully download. The bound directory has files in it, but not a masterLog.0 file.
I'm attempting to run version 1.4.4.9 (as is the default, and also the current version on steam).

**Comment by ich777** [comment]
@shadow7412 sorry but I can't reproduce this on my Unraid server, can you post the `docker run` command please?

Here is the output from my machine: [terraria.log](https://github.com/ich777/docker-terraria-server/files/10710539/terraria.log)
(I stripped the log a bit because the world generation produces much noise...)

**Comment by shadow7412** [comment]
```
docker run
  -d
  --name='Terraria'
  --net='bridge'
  -e TZ="Australia/Sydney"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="[redacted]"
  -e HOST_CONTAINERNAME="Terraria"
  -e 'TERRARIA_SRV_V'='1.4.4.9'
  -e 'GAME_PARAMS'='-config serverconfig.txt'
  -e 'UID'='99'
  -e 'GID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/terraria.png'
  -p '7778:7777/tcp'
  -p '9013:8080/tcp'
  -v '/mnt/cache/appdata/terraria':'/serverdata/serverfiles':'rw'
  --restart=unless-stopped 'ich777/terrariaserver'
```

**Comment by shadow7412** [comment]
I realised I started getting a `OCI runtime exec failed: exec failed: unable to start container process: open /dev/ptmx: no space left on device: unknown` error whenever trying to attach a terminal to a docker container.

So I rebooted, and now things are working as they're supposed to. Sorry for bothering you.
