### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by hol430** [ich777/docker-terraria-server#5]
Hi, I've recently set up a server based on this image on an ARM64 server (raspberry pi 4). It seems to be working well and required only minor changes to the dockerfile (mainly using system mono to run the server). I'd be happy to feed this back if you're interested in having these changes here. Otherwise, feel free to close this and I'll just leave a link to my changes in case it helps anyone:

https://github.com/hol430/docker-terraria-server/tree/tmodloader_arm64

**Comment by ich777** [comment]
First of all thank you for that! :)

I have already made a PR on your repo that changes to the latest Bullseye base image, but I have to say I don't saw that you've also installed Mono there.

If you want to, I can create a Mono baseimage for arm64 (currently I only have a [base image for amd64 available](https://hub.docker.com/r/ich777/mono-baseimage)) and build it so that it is available on Docker Hub. ;)

Having no issue building for arm64 because I anyways build [Firefox](https://hub.docker.com/r/ich777/firefox/tags) and [Thunderbird](https://hub.docker.com/r/ich777/thunderbird/tags) containers for those platforms.

**Comment by hol430** [comment]
Mono base image could be a good idea - my changes are specifically for the tmodloader image, but if you ever wanted arm versions of the vanilla or tshock images, having an arm mono base image would save from hardcoding the same mono installation steps in multiple places. My main requirement would be latest mono - I tried yesterday mono 5.18 (which I think was the latest in the raspbian repos...) but ran into bugs which were ultimately solved by upgrading to mono 6.12 from the debian repos.

Good poitn about debian base image version - I'm not super familiar with debian so happy to go with whatever you think is best there. I've updated my branch to use debian-baseimage:latest_arm64 and have made a PR (#6). Let me know if you want any changes made.

**Comment by ich777** [comment]
@hol430 baseimage is now ready: [Click](https://hub.docker.com/r/ich777/mono-baseimage/tags)
If you want to use it simply change `FROM ich777/debian-baseimage:latest_arm64` to `FROM ich777/mono-baseimage:latest_arm64` and remove the code for the Mono installation from the `Dockerfile`.

Please keep me updated when you've done this and I will create a PR from your to my repo.

BTW thank you for the PR and everything, PRs are rare on my repos... :'(

**Comment by hol430** [comment]
Great, thanks for that - I've just updated the dockerfile to use mono-baseimage.

Thanks for maintaining all of this btw - it's certainly saved me a lot of time, and probably others as well :).

**Comment by ich777** [comment]
@hol430 I will pull the changes over to my repo (including credits :smiley:) and build the container so you can pull it from my Docker Hub if you want to, please report back if everything is working properly after that, currently I have no Pi set up to test this on my own.

**Comment by hol430** [comment]
Thanks - I've just updated my pi to use the arm64 image on your dockerhub and everything seems to be working well. Thanks heaps for that!
